name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        nim: [2.0.14]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}

    - name: Install Nim
      uses: iffy/install-nim@v4
      with:
        version: ${{ matrix.nim }}

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install test node
      working-directory: testnode
      run: npm install

    - name: Run test node
      working-directory: testnode
      run: npm start &

    - name: Build
      run: nimble install -y --debug

    - name: Test
      run: nimble test -y

  status:
    if: always()
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')  || contains(needs.*.result, 'skipped') }}
        run: exit 1
