name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nim: [1.2.16, stable]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Nim
      uses: iffy/install-nim@v3
      with:
        version: ${{ matrix.nim }}
    - name: Install NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install test node
      working-directory: testnode
      run: npm install
    - name: Run test node
      working-directory: testnode
      run: npm start &
    - name: Build
      run: nimble install -y
    - name: Test
      run: nimble test -y
